// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns HTTP 200 if the API server is running. No auth required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_pykul_ai-ranger_workers_internal_api.healthResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/agents/{id}": {
            "delete": {
                "description": "Sets an agent's status to 'revoked', preventing further event submission.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Revoke agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Agent revoked"
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Agent not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/admin/settings": {
            "get": {
                "description": "Returns the current org settings including the masked webhook URL.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get org settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_pykul_ai-ranger_workers_internal_api.SettingsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates the webhook URL for the organization. The URL must be HTTPS.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Update org settings",
                "parameters": [
                    {
                        "description": "Settings update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_pykul_ai-ranger_workers_internal_api.SettingsUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_pykul_ai-ranger_workers_internal_api.SettingsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/admin/settings/test": {
            "post": {
                "description": "Fires a test webhook to the configured URL for the organization.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Test webhook",
                "responses": {
                    "200": {
                        "description": "Webhook delivered",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No webhook configured",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "Webhook delivery failed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/admin/tokens": {
            "post": {
                "description": "Creates a new enrollment token for agent enrollment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create enrollment token",
                "parameters": [
                    {
                        "description": "Token creation request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_pykul_ai-ranger_workers_internal_api.TokenCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github.com_pykul_ai-ranger_workers_internal_api.TokenCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/admin/tokens/{id}": {
            "delete": {
                "description": "Deletes an enrollment token by ID, preventing further enrollments.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Revoke enrollment token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Token revoked"
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/dashboard/fleet": {
            "get": {
                "description": "Returns all enrolled agents with hostname, OS, version, last seen, and status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fleet"
                ],
                "summary": "Get fleet listing",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.FleetAgent"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github.com_pykul_ai-ranger_workers_internal_api.SettingsResponse": {
            "type": "object",
            "properties": {
                "org_id": {
                    "type": "string"
                },
                "webhook_url": {
                    "type": "string"
                }
            }
        },
        "github.com_pykul_ai-ranger_workers_internal_api.SettingsUpdateRequest": {
            "type": "object",
            "properties": {
                "org_id": {
                    "type": "string"
                },
                "webhook_url": {
                    "type": "string"
                }
            }
        },
        "github.com_pykul_ai-ranger_workers_internal_api.TokenCreateRequest": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "max_uses": {
                    "type": "integer"
                },
                "org_id": {
                    "type": "string"
                }
            }
        },
        "github.com_pykul_ai-ranger_workers_internal_api.TokenCreateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "max_uses": {
                    "type": "integer"
                },
                "org_id": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "github.com_pykul_ai-ranger_workers_internal_api.healthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_api.SettingsResponse": {
            "type": "object",
            "properties": {
                "org_id": {
                    "type": "string"
                },
                "webhook_url": {
                    "type": "string"
                }
            }
        },
        "internal_api.SettingsUpdateRequest": {
            "type": "object",
            "properties": {
                "org_id": {
                    "type": "string"
                },
                "webhook_url": {
                    "type": "string"
                }
            }
        },
        "internal_api.TokenCreateRequest": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "max_uses": {
                    "type": "integer"
                },
                "org_id": {
                    "type": "string"
                }
            }
        },
        "internal_api.TokenCreateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "max_uses": {
                    "type": "integer"
                },
                "org_id": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_api.healthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "store.FleetAgent": {
            "type": "object",
            "properties": {
                "agentVersion": {
                    "type": "string"
                },
                "enrolledAt": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "id": {
                    "description": "generated on device",
                    "type": "string"
                },
                "lastSeenAt": {
                    "type": "string"
                },
                "orgID": {
                    "type": "string"
                },
                "os": {
                    "description": "\"linux\" | \"macos\" | \"windows\"",
                    "type": "string"
                },
                "osUsername": {
                    "type": "string"
                },
                "status": {
                    "description": "\"active\" | \"revoked\"",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AI Ranger Query API",
	Description:      "Dashboard and fleet management endpoints for AI Ranger.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
